---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - master

  - name: worker-node-1
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - workers

provisioner:
  name: ansible
  config_file: ../../ansible.cfg
  env:
    ANSIBLE_ROLES_PATH: ../../m.filatova_ansible/roles
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  name: full-cluster-k8s
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy