---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k8s-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  config_file: ../../ansible.cfg
  env:
    ANSIBLE_ROLES_PATH: ../../m.filatova_ansible/roles
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
scenario:
  name: full
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy