---
- name: Install kubeadm and kubectl
  ansible.builtin.apt:
    name:
      - kubeadm=1.32.13-1.1
      - kubectl=1.32.13-1.1
    state: present
    update_cache: true
  register: kubeadm_install_result
  until: kubeadm_install_result is succeeded
  retries: 3
  delay: 15

- name: Hold kubeadm and kubectl packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl
  when: not ansible_check_mode