apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currency-api-production
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=mfilatova/currency-rest-api
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/api.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: m.filatova/manifests
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:helm/currency-api/values-production.yaml
    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
spec:
  project: currency-api
  source:
    repoURL: https://education-git.yadro.com/education/devops/2026/m.filatova/app.git
    targetRevision: m.filatova/manifests
    path: helm/currency-api
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: currency-api-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true