---
- name: Verify crio installation
  hosts: all
  become: true
  tasks:
    - name: Check if cri-o is installed
      ansible.builtin.command: which crio
      register: crio_check
      changed_when: false
    
    - name: Assert cri-o is installed
      ansible.builtin.assert:
        that:
          - crio_check.rc == 0

    - name: Get crio version
      ansible.builtin.command: crio --version
      register: version_output
      changed_when: false

    - name: Show crio version
      ansible.builtin.debug:
        var: version_output.stdout_lines
