---
galaxy_info:
  author: m.filatova
  description: Prepare Ubuntu 22.04 nodes for Kubernetes and install kubelet.
  company: yadro
  license: GPL-2.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - kubernetes
    - kubelet
    - ubuntu
    - systemd

dependencies: []
