---
galaxy_info:
  author: m.filatova
  description: Install and configure CRI-O for Kubernetes nodes on Ubuntu 22.04.
  company: yadro
  license: GPL-2.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - kubernetes
    - crio
    - container
    - ubuntu

dependencies: []
