---
- name: Initialize Kubernetes master node
  hosts: master
  become: true
  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/main.yml
  roles:
    - role: k8s_master

- name: Join worker nodes to cluster
  hosts: workers
  become: true
  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/main.yml
  vars:
    kubeadm_join_command: "{{ hostvars[groups['master'][0]]['kubeadm_join_command'] | default('') }}"
  roles:
    - role: k8s_worker